### PR TITLE
fix(zset): fix wrong func name

### PR DESCRIPTION
**Pull request by SilverRainZ**

### CODE REVIEW

**Comment by zhangyunhao116** [comment]
It would be nice if we could add a test for this PR for preventing other issues like this, looks like we don't test each function before it is called by the user for now.

**Comment by SilverRainZ** [comment]
Test added :D

**Comment by zhangyunhao116** [comment]
Looks like we should fix the license checker, the latest version of the checker is not working for now. Maybe we can follow the Kitex's flow, change the version from `https://github.com/bytedance/gopkg/blob/develop/.github/workflows/push-check.yml#L26` to `https://github.com/cloudwego/kitex/blob/develop/.github/workflows/pr-check.yml#L11`.

**Comment by SilverRainZ** [comment]
I think this is another issue, we can merge this first?

**Review by zhangyunhao116 — APPROVED** [review]

**Review by zhangyunhao116 — APPROVED** [review]

**Review by luchsh — APPROVED** [review]

**Pull request merged**
