### PR TITLE
chore: fix gctuner tests

### PR DESCRIPTION
**Pull request by joway**
- TestChangeGCPercent will change some global vars that make tests fail. so remove it.
- change tests logic to make it more robust

### CODE REVIEW

**Comment by zhangyunhao116** [comment]
Hmm, I can still reproduce the error via `go test -count=100` (Go 1.19 linux/amd64).
```
--- FAIL: TestFinalizer (0.04s)
    finalizer_test.go:36: cannot exec finalizer callback after f has been gc
    finalizer_test.go:45: 
                Error Trace:    finalizer_test.go:45
                Error:          Not equal: 
                                expected: 17
                                actual  : 16
                Test:           TestFinalizer
    finalizer_test.go:47: 
                Error Trace:    finalizer_test.go:47
                Error:          Not equal: 
                                expected: 17
                                actual  : 16
                Test:           TestFinalizer
    finalizer_test.go:49: 
                Error Trace:    finalizer_test.go:49
                Error:          Not equal: 
                                expected: 17
                                actual  : 16
                Test:           TestFinalizer
```

**Comment by joway** [comment]
@zhangyunhao116 plz take another look, thanks

```
go test -count=100 -timeout=10s
PASS
ok  	github.com/bytedance/gopkg/util/gctuner	8.687s
```

**Comment by zhangyunhao116** [comment]
There is another one, but it looks like a small probability error. Not sure if it is a platform-related issue(running on DevBox, Go1.19 linux/amd64)?

```
$ go test -count=100
--- FAIL: TestFinalizer (0.04s)
    finalizer_test.go:36: cannot exec finalizer callback after f has been gc
```

**Comment by joway** [comment]
@zhangyunhao116 Hi, I think the last commit fixed everything...

The reason why these test cases are not stable is that different go version has different GC behaviors.
So I manual GC for finalizer test to hide version differences.

And since go GC depends on runtime memory allocate, if the test cases runs too many times, the memory allocate peak may will be changed out of expectation. So I also change the TestTuner test case to make it more robust.

**Review by zhangyunhao116 — APPROVED** [review]
Thanks!

**Review by PureWhiteWu — APPROVED** [review]

**Pull request merged**
